name: Mirror Sync

on:
  push:

jobs:
  sync-mirror:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'inpsyde' && !contains(github.event.head_commit.message, 'skip mirror') }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.INPSYDE_BOT_SSH_PRIVATE_KEY }}

      - run: |
          git config --global user.email "${{ secrets.INPSYDE_BOT_EMAIL }}"
          git config --global user.name "${{ secrets.INPSYDE_BOT_USER }}"
          git push --mirror --force git@github.com:Inpsyde-Global-Service-Provider/gutenberg-versions-mirror.git